export const ORDER_USER_LIST_REQUEST = "ORDER_USER_LIST_REQUEST";
export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";
export const ORDER_USER_LIST_FAIL = "ORDER_USER_LIST_FAIL";
export const ORDER_USER_LIST_RESET = "ORDER_USER_LIST_RESET";
